### ISSUE TITLE
Inconsistent accidentals

### ISSUE THREAD

**Issue by dscorbett** [notofonts/music#4]
### Font
NotoMusic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/9176dad6dc8ee09b552f9f6de36c4e9b19f8e7ea/phaseIII_only/unhinted/otf/NotoMusic/NotoMusic-Regular.otf
Date: 2018-09-27

### Font version
Version 2.000

### Issue
The accidentals in the BMP are drawn in a different style than those in the SMP. The quarter-tone accidentals are smaller and higher than the others.

### Character data
♭𝄬𝄳 ♮𝄮 ♯𝄰𝄲
U+266D MUSIC FLAT SIGN
U+1D12C MUSICAL SYMBOL FLAT UP
U+1D133 MUSICAL SYMBOL QUARTER TONE FLAT
U+266E MUSIC NATURAL SIGN
U+1D12E MUSICAL SYMBOL NATURAL UP
U+266F MUSIC SHARP SIGN
U+1D130 MUSICAL SYMBOL SHARP UP
U+1D132 MUSICAL SYMBOL QUARTER TONE SHARP

### Screenshot
![♭𝄬𝄳 ♮𝄮 ♯𝄰𝄲](https://user-images.githubusercontent.com/1124347/46257829-abb58400-c48e-11e8-8d9a-957073490819.png)

**Comment by SKing-2003** [comment]
The accidental inconsistency seems to be fixed, though the quarter tones are still as originally described:
![image](https://user-images.githubusercontent.com/107930743/175309208-8275c6c9-539a-413c-939f-790ae8697338.png)

**Comment by simoncozens** [comment]
Symbols does the same (quarter-sized quarter tones), FWIW - and more to the point, so does the Unicode code chart. So, in the absence of any evidence it shouldn't be like this, I'm keeping it as it is.
