### ISSUE TITLE
Overlapping U+1D17C MUSICAL SYMBOL COMBINING STACCATO

### ISSUE THREAD

**Issue by dscorbett** [notofonts/music#9]
### Font
NotoMusic-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/music/releases/tag/NotoMusic-v2.002
Date: 2022-09-11

### Font version
Version 2.002

### Issue
Multiple instances of U+1D17C MUSICAL SYMBOL COMBINING STACCATO overlap each other. See [here](https://music.stackexchange.com/questions/94311/two-dots-below-a-note-in-the-bass-clef) for an attestation.

### Character data
𝅘𝅥𝅼𝅼
U+1D15F MUSICAL SYMBOL QUARTER NOTE
U+1D17C MUSICAL SYMBOL COMBINING STACCATO
U+1D17C MUSICAL SYMBOL COMBINING STACCATO

### Screenshot
![𝅘𝅥𝅼𝅼](https://user-images.githubusercontent.com/1124347/189548685-83941a17-66e8-4702-ab9e-ff0adf8707b9.png)

**Comment by dscorbett** [comment]
There are also triple and quadruple staccatos.

**Comment by simoncozens** [comment]
"Just look at the string and *think* about plucking it."
